server:
  port: 8080

spring:
  application:
    name: BeStudyApplication

datasource:
  url: jdbc:h2:mem:testdb
  driver-class-name: org.h2.Driver
  username: sa
  password:

hibernate:
  ddl-auto: update
  show-sql: true

logging:
  level:
    root: info
    org.springframework: info
    com.example.be_study: debug