version: '3.6'
services:
  mysql:
    container_name: house-mysql
    image: mysql:8.0
    platform: linux/amd64
    volumes:
      - ./my.cnf:/etc/mysql/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=house
      - MYSQL_USER=bestudy
      - MYSQL_PASSWORD=bestudy
    ports:
      - 3306:3306
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
